function Page(divId){
    let _divId = divId;
    function init(){
        $("#"+_divId).empty();
        $("#"+_divId).append("<h1>THE PAGE WAS GENERATED BY JS AND JQUERY</h1>");
    }
    init();
}
